#!/usr/bin/env python
from arrrgs import arg, command, global_args, no_command, run

from libhapm.manifest import Manifest
from libhapm.manager import PackageManager

STORAGE_DIR = ".hapm"
MANIFEST_PATH = "hapm.yaml"

global_args(
    arg('--manifest', '-m', default=MANIFEST_PATH, help="Manifest path"),
    arg('--storage', '-s', default=STORAGE_DIR, help="Storage location")
)


@no_command()
def sync(args, store: PackageManager):
    """Synchronizes local versions of components with the manifest."""
    manifest = Manifest(args.manifest)
    manifest.load()
    store.apply(manifest.values)

@command(
    arg('--type', '-t', required=True, default=None, help="Package type"),
    arg('path', default=None, help="Output path")
)
def put(args, store: PackageManager):
    """Synchronizes local versions of components with the manifest."""
    store.export(args.type, args.path)

@command()
def updates(args, store: PackageManager):
    """Prints available packages updates."""
    print(store.updates())
    # if args.dry is True:
    #     exit(0)

@command(name="list")
def list_packages(_, store: PackageManager):
    """Print current version of components."""
    for d in store.descriptions():
        url, version, kind = d["url"], d["version"], d["kind"]
        print(f"{kind} {url}@{version}")


def prepare(args):
    """Creates HAPM context"""
    return args, PackageManager(args.storage)


if __name__ == "__main__":
    run(prepare=prepare)
